### ISSUE TITLE
QML import could not be resolved in any of the import paths error ,build UsingNativeCameraAndImagePicker

### ISSUE THREAD

**Issue by kongtian888** [minixxie/wpp-qt#3]
Hello,I am getting error:

Warning: QML import could not be resolved in any of the import paths: wpp.qt.SMS
Warning: QML import could not be resolved in any of the import paths: wpp.qt.NativeDateTimePicker
Warning: QML import could not be resolved in any of the import paths: wpp.qt.NativeCamera
Warning: QML import could not be resolved in any of the import paths: wpp.qt.ImagePicker
Warning: QML import could not be resolved in any of the import paths: wpp.qt.IOSTimeZonePicker
Warning: QML import could not be resolved in any of the import paths: QtWebKit
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: HelperWidgets

when try build UsingNativeCameraAndImagePicker on android. How to solve ?

This is .pro file:

TEMPLATE = app

QT += qml quick

SOURCES += main.cpp

RESOURCES += qml.qrc
OTHER_FILES += main.qml

include(deployment.pri)

include($$PWD/wpp-qt/wpp.pri)

DISTFILES += \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/AndroidManifest.xml \
    android/res/values/libs.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew \
    android/gradlew.bat

ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android

Thanks you.

**Comment by minixxie** [comment]
These are warnings only. Could it run up or it crashed?

**Comment by kongtian888** [comment]
Thank you for answer,I am building UsingNativeCameraAndImagePicker,
It does not run ,when start ,I only see black screen and  In application output I have a lot of java errors : May be because I did not set QML_IMPORT_PATH ? How do I set it, my project structure is like this : 
![gitquest](https://cloud.githubusercontent.com/assets/14229742/9973822/66c015ea-5eac-11e5-9d1c-90a0395693a6.png)

These are errors I am getting.
Thank you for help.
W/System.err(22717): java.lang.ClassNotFoundException: android.graphics.drawable.RippleDrawable
W/System.err(22717):    at java.lang.Class.classForName(Native Method)
W/System.err(22717):    at java.lang.Class.forName(Class.java:217)
W/System.err(22717):    at java.lang.Class.forName(Class.java:172)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:396)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:100)
W/System.err(22717):    at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:438)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.loadApplication(QtActivity.java:245)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.startApp(QtActivity.java:655)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:895)
W/System.err(22717):    at android.app.Activity.performCreate(Activity.java:5200)
W/System.err(22717):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
W/System.err(22717):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
W/System.err(22717):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
W/System.err(22717):    at android.app.ActivityThread.access$600(ActivityThread.java:146)
W/System.err(22717):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1240)
W/System.err(22717):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(22717):    at android.os.Looper.loop(Looper.java:137)
W/System.err(22717):    at android.app.ActivityThread.main(ActivityThread.java:5171)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
W/System.err(22717):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
W/System.err(22717):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(22717): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/RippleDrawable
W/System.err(22717):    ... 25 more
W/System.err(22717): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.RippleDrawable" on path: /data/app/org.qtproject.example.UsingNativeCameraAndImagePicker-1.apk
W/System.err(22717):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err(22717):    ... 25 more
W/System.err(22717): java.lang.ClassNotFoundException: android.graphics.drawable.AnimatedStateListDrawable
W/System.err(22717):    at java.lang.Class.classForName(Native Method)
W/System.err(22717):    at java.lang.Class.forName(Class.java:217)
W/System.err(22717):    at java.lang.Class.forName(Class.java:172)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:396)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:101)
W/System.err(22717):    at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:438)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.loadApplication(QtActivity.java:245)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.startApp(QtActivity.java:655)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:895)
W/System.err(22717):    at android.app.Activity.performCreate(Activity.java:5200)
W/System.err(22717):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
W/System.err(22717):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
W/System.err(22717):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
W/System.err(22717):    at android.app.ActivityThread.access$600(ActivityThread.java:146)
W/System.err(22717):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1240)
W/System.err(22717):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(22717):    at android.os.Looper.loop(Looper.java:137)
W/System.err(22717):    at android.app.ActivityThread.main(ActivityThread.java:5171)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
W/System.err(22717):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
W/System.err(22717):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(22717): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/AnimatedStateListDrawable
W/System.err(22717):    ... 25 more
W/System.err(22717): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.AnimatedStateListDrawable" on path: /data/app/org.qtproject.example.UsingNativeCameraAndImagePicker-1.apk
W/System.err(22717):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err(22717):    ... 25 more
W/System.err(22717): java.lang.ClassNotFoundException: android.graphics.drawable.VectorDrawable
W/System.err(22717):    at java.lang.Class.classForName(Native Method)
W/System.err(22717):    at java.lang.Class.forName(Class.java:217)
W/System.err(22717):    at java.lang.Class.forName(Class.java:172)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.getClass(ExtractStyle.java:396)
W/System.err(22717):    at org.qtproject.qt5.android.ExtractStyle.<init>(ExtractStyle.java:102)
W/System.err(22717):    at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:438)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.loadApplication(QtActivity.java:245)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.startApp(QtActivity.java:655)
W/System.err(22717):    at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:895)
W/System.err(22717):    at android.app.Activity.performCreate(Activity.java:5200)
W/System.err(22717):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
W/System.err(22717):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
W/System.err(22717):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
W/System.err(22717):    at android.app.ActivityThread.access$600(ActivityThread.java:146)
W/System.err(22717):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1240)
W/System.err(22717):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(22717):    at android.os.Looper.loop(Looper.java:137)
W/System.err(22717):    at android.app.ActivityThread.main(ActivityThread.java:5171)
W/System.err(22717):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(22717):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(22717):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
W/System.err(22717):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
W/System.err(22717):    at dalvik.system.NativeStart.main(Native Method)
W/System.err(22717): Caused by: java.lang.NoClassDefFoundError: android/graphics/drawable/VectorDrawable
W/System.err(22717):    ... 25 more
W/System.err(22717): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.VectorDrawable" on path: /data/app/org.qtproject.example.UsingNativeCameraAndImagePicker-1.apk
W/System.err(22717):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/System.err(22717):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/System.err(22717):    ... 25 more
W/ResourceType(22717): Skipping entry 0x10804dd in package table 0 because it is not complex!

W/Qt A11Y (22717): Could not activate platform accessibility.
E/NavigationBar(22717): meta-data ==> set Navi Bg (package:org.qtproject.example.UsingNativeCameraAndImagePicker, portResource ID:0, landResource ID:0, alpha:0)

E/NavigationBar(22717): meta-data ==> set Navi Bg (package:org.qtproject.example.UsingNativeCameraAndImagePicker, portResource ID:0, landResource ID:0, alpha:0)
W/Adreno-GSL(22717): <get_panel_settings:3801>: Android framework reported version 2. So, don't force ES30

E/Wpp:setSoftInputMode(22717): setSoftInputMode...
E/Wpp:setSoftInputMode(22717): setSoftInputMode...mode=16
E/Wpp:setSoftInputMode(22717): setSoftInputMode...
W/libUsingNativeCameraAndImagePicker.so(22717): (null):0 ((null)): QQmlApplicationEngine failed to load component
W/libUsingNativeCameraAndImagePicker.so(22717): (null):0 ((null)): qrc:/main.qml:3 module "QtQuick.Controls" version 1.4 is not installed
W/libUsingNativeCameraAndImagePicker.so(22717):

**Comment by lanbudao** [comment]
These are warnings only. You don't need to care about it. At least, I didn't care about it when I found it.
